name: monthly
description: A cross-platform budgeting application.
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # Your SDK version. Matches your provided `^3.8.1`.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # Standard iOS-style icons

  # --- Monthly App Specific Core Dependencies ---

  # State Management (Provider is simple and widely used)
  provider: ^6.0.5

  # Local Database (SQLite)
  sqflite: ^2.3.0             # SQLite database integration
  sqflite_common_ffi: ^2.3.2  # <--- ADD THIS LINE for desktop support
  path_provider: ^2.1.1       # Helps find appropriate storage paths for DB
  path: ^1.8.3                 # For cross-platform path manipulation utilities

  # Utility & Formatting
  intl: ^0.18.1               # For internationalization (dates, currencies, numbers)
  uuid: ^4.2.1                # For generating unique IDs for transactions, accounts, etc.

  # UI & Icons
  fl_chart: ^0.65.0           # For creating beautiful charts and graphs (e.g., reports)
  font_awesome_flutter: ^10.6.0 # For a wider range of icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0     # Recommended lints for good coding practices
  build_runner: ^2.4.6      # Needed for code generation (e.g., for future JSON serialization or `drift`)

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic